# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 10:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180313_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
