# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180314_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire',
            field=models.CharField(max_length=50, verbose_name='Questionnaire name'),
        ),
    ]
