# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180314_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(1, 'Without variants'), (2, 'With variants'), (3, 'With several variants')], default=2, max_length=200),
        ),
        migrations.AlterField(
            model_name='variants',
            name='v1',
            field=models.CharField(max_length=200, verbose_name='Variant 1'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='v2',
            field=models.CharField(max_length=200, verbose_name='Variant 2'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='v3',
            field=models.CharField(max_length=200, verbose_name='Variant 3'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='v4',
            field=models.CharField(max_length=200, verbose_name='Variant 4'),
        ),
    ]
