# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180314_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Without variants'), (2, 'With variants'), (3, 'With several variants')], default=2),
        ),
    ]
