# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180314_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_right_variant',
            field=models.BooleanField(default=False),
        ),
    ]
