# Generated by Django 2.0.3 on 2018-03-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180315_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='is_right_variant',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_num',
            field=models.PositiveIntegerField(verbose_name='Number of question in the questionnaire'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete='cascade', to='main.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete='cascade', to='main.Question'),
        ),
        migrations.AddField(
            model_name='rightvariants',
            name='question',
            field=models.ForeignKey(on_delete='cascade', to='main.Question'),
        ),
        migrations.AddField(
            model_name='rightvariants',
            name='variant',
            field=models.ForeignKey(on_delete='cascade', to='main.Variant'),
        ),
    ]
