# Generated by Django 2.0.3 on 2018-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180323_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RightVariants',
            new_name='RightVariant',
        ),
    ]
