# Generated by Django 2.0.3 on 2018-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180323_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightvariant',
            name='variant',
            field=models.ForeignKey(limit_choices_to={'question': models.ForeignKey(on_delete='cascade', to='main.Question')}, on_delete='cascade', to='main.Variant'),
        ),
    ]
