# Generated by Django 2.0.3 on 2018-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180323_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightvariant',
            name='variant',
        ),
        migrations.AddField(
            model_name='rightvariant',
            name='variant',
            field=models.ManyToManyField(to='main.Variant'),
        ),
    ]
