# Generated by Django 2.0.3 on 2018-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180323_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightvariant',
            name='variant',
            field=models.ForeignKey(on_delete='cascade', to='main.Variant'),
        ),
    ]
