# Generated by Django 2.0.3 on 2018-03-28 11:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180323_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('data', models.DateTimeField(verbose_name='Дата и время прохорждения тестирования')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Вопросник', 'verbose_name_plural': 'Вопросники'},
        ),
        migrations.AlterModelOptions(
            name='rightvariant',
            options={'verbose_name': 'Правильный ответ', 'verbose_name_plural': 'Правильные ответы'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_num',
            field=models.PositiveIntegerField(verbose_name='Номер вопроса в вопроснике'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Вопрос без вариантов ответа'), (2, 'Вопрос с одним вариантом ответа'), (3, 'Впорос с несколькими вариантами ответа')], default=2, verbose_name='Тип вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete='cascade', to='main.Questionnaire', verbose_name='Название вопросника'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire',
            field=models.CharField(max_length=50, verbose_name='Название вопросника'),
        ),
        migrations.AlterField(
            model_name='rightvariant',
            name='question',
            field=models.ForeignKey(on_delete='cascade', to='main.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='rightvariant',
            name='variant',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='question', chained_model_field='question', on_delete=django.db.models.deletion.CASCADE, to='main.Variant', verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete='cascade', to='main.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant',
            field=models.CharField(max_length=200, verbose_name='Вариант ответа'),
        ),
    ]
