# Generated by Django 2.0.3 on 2018-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180328_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='percent_result',
            field=models.FloatField(default=0, verbose_name='Процент правильных ответов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='results',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время прохорждения тестирования'),
        ),
    ]
