# Generated by Django 2.0.3 on 2018-03-29 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_auto_20180329_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='user_name',
        ),
        migrations.AddField(
            model_name='results',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete='cascade', to='main.Questionnaire', verbose_name='Вопросника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='user',
            field=models.ForeignKey(default=1, on_delete='cascade', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название вопросника'),
        ),
    ]
