# Generated by Django 2.0.3 on 2018-03-29 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180329_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.OneToOneField(on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Пользователя'),
        ),
    ]
