# Generated by Django 2.0.3 on 2018-03-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180329_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='results',
            name='user',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
