# Generated by Django 2.0.3 on 2018-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='percent_result',
            field=models.IntegerField(verbose_name='Процент правильных ответов'),
        ),
    ]
