# Generated by Django 2.0.3 on 2018-04-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20180330_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='data',
            new_name='date',
        ),
    ]
