# Generated by Django 2.0.3 on 2018-04-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20180403_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='results',
            name='user',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
