# Generated by Django 2.0.3 on 2018-04-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20180411_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'question_num')},
        ),
    ]
